### ISSUE TITLE
关于移动端的声音播放和前端显示的一点问题

### ISSUE THREAD

**Issue by Means88** [LoveCallProject/lovecall-frontend#6]
-  App 里面无法播放声音
-  Chrome 的 User Agent 除了系统的版本以外，好像还和本身的版本有关，所以我这里用 43 版的 Chrome 没办法显示下载选项，更新为 47 版以后就正常了。其他浏览器暂时没发现类似问题。

![chrome_show](http://i11.tietuku.com/f7c6c099e6ad330ft.jpg)![chrome_option](http://i11.tietuku.com/36802a6b0bced3d2t.jpg)
-  UC 浏览器显示不正常，其他浏览器暂时没发现类似问题。

![uc_show](http://i11.tietuku.com/e1d38d5298def5c8t.jpg)

。。最后dalao们辛苦了

**Comment by disoul** [comment]
花厨同好啊  
关于app无法播放声音应该有可能时缓冲区设置问题
感谢提出的问题，我们会尽力修改
